require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ShootingsController do

  # This should return the minimal set of attributes required to create a valid
  # Shooting. As you add validations to Shooting, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ShootingsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all shootings as @shootings" do
      shooting = Shooting.create! valid_attributes
      get :index, {}, valid_session
      assigns(:shootings).should eq([shooting])
    end
  end

  describe "GET show" do
    it "assigns the requested shooting as @shooting" do
      shooting = Shooting.create! valid_attributes
      get :show, {:id => shooting.to_param}, valid_session
      assigns(:shooting).should eq(shooting)
    end
  end

  describe "GET new" do
    it "assigns a new shooting as @shooting" do
      get :new, {}, valid_session
      assigns(:shooting).should be_a_new(Shooting)
    end
  end

  describe "GET edit" do
    it "assigns the requested shooting as @shooting" do
      shooting = Shooting.create! valid_attributes
      get :edit, {:id => shooting.to_param}, valid_session
      assigns(:shooting).should eq(shooting)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Shooting" do
        expect {
          post :create, {:shooting => valid_attributes}, valid_session
        }.to change(Shooting, :count).by(1)
      end

      it "assigns a newly created shooting as @shooting" do
        post :create, {:shooting => valid_attributes}, valid_session
        assigns(:shooting).should be_a(Shooting)
        assigns(:shooting).should be_persisted
      end

      it "redirects to the created shooting" do
        post :create, {:shooting => valid_attributes}, valid_session
        response.should redirect_to(Shooting.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved shooting as @shooting" do
        # Trigger the behavior that occurs when invalid params are submitted
        Shooting.any_instance.stub(:save).and_return(false)
        post :create, {:shooting => {}}, valid_session
        assigns(:shooting).should be_a_new(Shooting)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Shooting.any_instance.stub(:save).and_return(false)
        post :create, {:shooting => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested shooting" do
        shooting = Shooting.create! valid_attributes
        # Assuming there are no other shootings in the database, this
        # specifies that the Shooting created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Shooting.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => shooting.to_param, :shooting => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested shooting as @shooting" do
        shooting = Shooting.create! valid_attributes
        put :update, {:id => shooting.to_param, :shooting => valid_attributes}, valid_session
        assigns(:shooting).should eq(shooting)
      end

      it "redirects to the shooting" do
        shooting = Shooting.create! valid_attributes
        put :update, {:id => shooting.to_param, :shooting => valid_attributes}, valid_session
        response.should redirect_to(shooting)
      end
    end

    describe "with invalid params" do
      it "assigns the shooting as @shooting" do
        shooting = Shooting.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Shooting.any_instance.stub(:save).and_return(false)
        put :update, {:id => shooting.to_param, :shooting => {}}, valid_session
        assigns(:shooting).should eq(shooting)
      end

      it "re-renders the 'edit' template" do
        shooting = Shooting.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Shooting.any_instance.stub(:save).and_return(false)
        put :update, {:id => shooting.to_param, :shooting => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested shooting" do
      shooting = Shooting.create! valid_attributes
      expect {
        delete :destroy, {:id => shooting.to_param}, valid_session
      }.to change(Shooting, :count).by(-1)
    end

    it "redirects to the shootings list" do
      shooting = Shooting.create! valid_attributes
      delete :destroy, {:id => shooting.to_param}, valid_session
      response.should redirect_to(shootings_url)
    end
  end

end
